### ISSUE TITLE
Task that checks water sensor for water leaks

### ISSUE THREAD

**Issue by lymacasm** [uvic-auvic/firmware#20]
Write a task that monitors the water sensor to ensure there is no leaks. Devise a way to alert the user if there is a leak (LED light show, UART cry for help, raise a GPIO output high, etc.). The water sensor can be read from the ADC functions in uvic-auvic/Firmware-Power_Board_1.0#4.

**Comment by anijjar** [comment]
Wont do because we have a new power board
