### ISSUE TITLE
ADC driver for STM32F4

### ISSUE THREAD

**Issue by poornack** [uvic-auvic/firmware#33]
**Problem Definitions**: An ADC driver is required for all STM32F4 based controllers on the AUV

**Task**: Write a shared ADC driver that can be configured to be used on all our STM32F4 based controllers. The driver should use DMA where possible.

There is only one public function this in module.

`uint16_t ADC_getChannelData(const ADC_channel_E channel)`
Returns the raw ADC value of the given channel. The range should be [0, 4095].

This code needs to run on all controllers. Therefore, it needs to have component specific files to configure it for each controller. `ADC_channel_E` should be defined in the component specific header file. For now, get it working on the power board only.

The new power board will have the following ADC inputs.
Depth Sensor
Internal 5V Supply Voltage

**Comment by anijjar** [comment]
Done
