### ISSUE TITLE
SPI driver for STM32F413

### ISSUE THREAD

**Issue by poornack** [uvic-auvic/firmware#34]
**Problem Description**: A SPI driver is needed for the STM32F413 based components on the sub

**Task**: Write a SPI driver, write unit tests and perform hardware tests. The code should be modular enough to use on different components. Use component specific files if necessary. Follow the below API.

**API**:

File name:; `SPI.c` `SPI.h`

`void SPI_init(void);`
`void SPI_run(void);`
Recommend to put in 1ms or 10ms task. 

`bool SPI_send(SPI_channel_E channel, const uint8_t * const data, const uint8_t length);`
Sends the data on the SPI bus. Internally, this function should place the data to be sent in a buffer. The run task should send the data.
`channel`: SPI bus/channel to use
`data`: Pointer to the data to send
`length`: Length of the data pointed to by `data`
Returns TRUE if successfully sent or placed on buffer, FALSE otherwise (channel not valid, length is 0, length it too long, data is NULL)

`bool SPI_sendAndReceive(SPI_channel_E channel, const uint8_t * const data, const uint8_t length);`
Sends and receives data on the SPI bus. Once data is received, a callback should be called. If 1 byte is to be sent followed by 4 bytes of reception, `length` should be equal to 5 and `data` should be 5 bytes long.
`channel`: SPI bus/channel to use
`data`: Pointer to the data to send
`length`: Length of the data pointed to by data
Returns TRUE if successfully sent or placed on buffer, FALSE otherwise (channel not valid, length is 0, length it too long, data is NULL)

## Current Status
- Debugging in progress
- Checking compatibility with circular buffer
- have a testing plan
## Next Steps
- debugging peripherals
- bring scope home
-

**Comment by anijjar** [comment]
Wont do because issue is old
