### ISSUE TITLE
Implement RPM Detection on Motor Controller from ESC SPD Lines

### ISSUE THREAD

**Issue by cartercooper** [uvic-auvic/firmware#51]
The ESC's used for Motor Controller 3 are able to output a square wave on their SPD lines corresponding to motor phases. These signals can easily be translated into RPM of the Motor.

Implement code to read the SPD lines and calculate the motor RPM.

Once completed, this could potentially be used to implement RPM control of the motor instead of the basic PWM control.

**Comment by anijjar** [comment]
Wont do because new motor controller was developed
