### ISSUE TITLE
Implement a 1D circular buffer

### ISSUE THREAD

**Issue by poornack** [uvic-auvic/firmware#6]
**Problem Description:** A one dimensional FIFO circular buffer required to buffer outgoing UART messages.

**Task:** Write and unit test a one dimensional circular buffer. This should be modular enough to use on different components. Use component specific files if necessary. Follow the below API:

`uint8_t circBuffer1D_getSpaceAvailable(const circBuffer1D_channel_E channel);`
Returns the number of bytes available in the specified buffer. Returns 0 if `channel` is not a valid channel.
 
`bool circBuffer1D_popByte(const circBuffer1D_channel_E channel, uint8_t * const dataToReturn);`
The oldest byte in the buffer is copied into `returnData`. Function returns true if successful. If buffer is empty, `returnData` is NULL or `channel` is not a valid channel, function returns false.

`bool circBuffer1D_pushByte(const circBuffer1D_channel_E channel, const uint8_t data);`
`data` is added to the buffer for the specified channel. Function returns true if successfully added. Function returns false if buffer is full, or `channel` is not a valid channel. 

`uint8_t circBuffer1D_pop(const circBuffer_channel_E channel, uint8_t * const dataToReturn)`
The entire buffer is copied into `dataToReturn` and the number of bytes copied is returned. The function returns 0 if `channel` is not a valid channel or the buffer is empty.

`bool circBuffer1D_push(const circBuffer1D_channel_E channel, const uint8_t * const data, const uint8_t size);`
`size` bytes from `data` is copied into the specified buffer. Function returns true if successfully copied. Function returns false if buffer is full, `size` is 0, `data` is NULL or `channel` is not a valid channel.

**Comment by poornack** [comment]
@cartercooper Can you confirm if all the requests in this issue are completed? If so, go ahead and close this issue.

**Comment by anijjar** [comment]
This issue was completed
